baseURL: 'https://example.com/'
languageCode: 'zh-cn'
title: '示例站点'

# 启用 Hugo 模块
module:
  imports:
    - path: github.com/allnationconnect/hugo-wordgate
      disable: false

# WordGate配置
wordgate:
  app_secret: "your-secret-key-here" # 请替换为实际的密钥
  app:
    name: "示例站点"
    description: "这是一个示例站点"
    currency: "CNY"
  
  # 应用配置
  config:
    smtp:
      host: "smtp.example.com"
      port: 465
      username: "your-email@example.com"
      password: "your-password"
      from_email: "your-email@example.com"
      from_name: "示例站点"
      reply_to_email: "your-email@example.com"
    
    security:
      code_expire: 600
    
    payment:
      enabled: true
      
  # 产品同步配置
  products:
    - "content/courses/*.md"

# 参数配置
params:
  description: "示例站点描述"
  logo: "/images/logo.png"
  wordgate:
    base_url: "https://api.wordgate.io" # WordGate API 服务地址
    app_code: "your-app-code-here" # 请填写 WordGate 应用代码
    enable_payment: true

# 输出配置
outputs:
  home: 
    - "HTML"
    - "RSS"
  section: 
    - "HTML"
    - "RSS"
  page: 
    - "HTML"

# 菜单配置
menu:
  main:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "课程"
      url: "/courses/"
      weight: 2
    - name: "用户中心"
      url: "/user/"
      weight: 3
    - name: "关于"
      url: "/about/"
      weight: 4 